const numberBtn = document.querySelectorAll('.number')
const operationBtn = document.querySelectorAll('.btn-operation')
const equalsBtn = document.querySelectorAll('.equals-btn')
const deletBtn = document.querySelectorAll('.btn-delete')
const btn-all-clear = document.querySelectorAll('.btn-all-clear')