const numberBtn = document.querySelectorAll('.number')
const operationBtn = document.querySelectorAll('.btn-operation')
const equalsBtn = document.querySelectorAll('.equals-btn')
const deletBtn = document.querySelectorAll('.btn-delete')
const clearAllBtn = document.querySelectorAll('.btn-clear-all')
const calculationDisp = document.querySelector('#calculation')
const resultDisp = document.querySelector('#result')